# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171208_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='texx',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='document',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
